name: Build and deploy PHP app to Azure Web App - laravel-api-jhordyn

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Generar documentación Swagger
        run: php artisan l5-swagger:generate

      - name: Crear carpeta Swagger en public
        run: mkdir -p public/swagger && cp -R vendor/swagger-api/swagger-ui/dist/* public/swagger/

      - name: Set correct permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Set execution permissions for startup.sh
        run: chmod +x startup.sh

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E38DA4259425437E86731C6032AEA7B9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22341873B37744F3BEF13B00F68E7DB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86C2D9F3473247BF9A8481868B1384E5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'laravel-api-jhordyn'
          slot-name: 'Production'
          package: .
